*** Starting uWSGI 2.0.22 (64bit) on [Mon Aug 14 19:56:04 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55c5f1e0c420
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 210514)
spawned uWSGI worker 1 (pid: 210515, cores: 1)
spawned uWSGI worker 2 (pid: 210516, cores: 1)
spawned uWSGI worker 3 (pid: 210517, cores: 1)
spawned uWSGI worker 4 (pid: 210518, cores: 1)
spawned uWSGI worker 5 (pid: 210519, cores: 1)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Mon Aug 14 20:01:05 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56174474a420
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 210617)
spawned uWSGI worker 1 (pid: 210621, cores: 1)
spawned uWSGI worker 2 (pid: 210622, cores: 1)
spawned uWSGI worker 3 (pid: 210623, cores: 1)
spawned uWSGI worker 4 (pid: 210624, cores: 1)
spawned uWSGI worker 5 (pid: 210625, cores: 1)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Mon Aug 14 20:04:21 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56534e5cf420
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 210695)
spawned uWSGI worker 1 (pid: 210698, cores: 1)
spawned uWSGI worker 2 (pid: 210699, cores: 1)
spawned uWSGI worker 3 (pid: 210700, cores: 1)
spawned uWSGI worker 4 (pid: 210701, cores: 1)
spawned uWSGI worker 5 (pid: 210702, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/1] 202.91.80.214 () {60 vars in 1021 bytes} [Mon Aug 14 20:08:19 2023] GET /static/style.css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210700|app: -1|req: -1/2] 202.91.80.214 () {60 vars in 1075 bytes} [Mon Aug 14 20:08:19 2023] GET /static/yuri_boi.png => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210700|app: -1|req: -1/3] 202.91.80.214 () {60 vars in 1071 bytes} [Mon Aug 14 20:08:19 2023] GET /static/favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/4] 202.91.80.214 () {60 vars in 1006 bytes} [Mon Aug 14 20:08:23 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/5] 202.91.80.214 () {56 vars in 944 bytes} [Mon Aug 14 20:08:23 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210701|app: -1|req: -1/6] 202.91.80.214 () {60 vars in 1006 bytes} [Mon Aug 14 20:08:24 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/7] 202.91.80.214 () {56 vars in 944 bytes} [Mon Aug 14 20:08:24 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/8] 202.91.80.214 () {60 vars in 1006 bytes} [Mon Aug 14 20:08:27 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210699|app: -1|req: -1/9] 202.91.80.214 () {56 vars in 944 bytes} [Mon Aug 14 20:08:27 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210698|app: -1|req: -1/10] 202.91.80.214 () {60 vars in 1006 bytes} [Mon Aug 14 20:08:27 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210698|app: -1|req: -1/11] 202.91.80.214 () {56 vars in 944 bytes} [Mon Aug 14 20:08:28 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210701|app: -1|req: -1/12] 202.91.80.214 () {60 vars in 1006 bytes} [Mon Aug 14 20:08:29 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210700|app: -1|req: -1/13] 202.91.80.214 () {56 vars in 944 bytes} [Mon Aug 14 20:08:29 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/14] 202.91.80.214 () {56 vars in 938 bytes} [Mon Aug 14 20:08:32 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/15] 202.91.80.214 () {60 vars in 1055 bytes} [Mon Aug 14 20:08:43 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/16] 202.91.80.214 () {56 vars in 960 bytes} [Mon Aug 14 20:08:43 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210701|app: -1|req: -1/17] 202.91.80.214 () {60 vars in 1055 bytes} [Mon Aug 14 20:08:44 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/18] 202.91.80.214 () {56 vars in 960 bytes} [Mon Aug 14 20:08:44 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/19] 202.91.80.214 () {60 vars in 1055 bytes} [Mon Aug 14 20:08:50 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210699|app: -1|req: -1/20] 202.91.80.214 () {56 vars in 960 bytes} [Mon Aug 14 20:08:50 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 210702|app: -1|req: -1/21] 202.91.80.214 () {56 vars in 960 bytes} [Mon Aug 14 20:09:03 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Mon Aug 14 20:27:19 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55f472a07420
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 211043)
spawned uWSGI worker 1 (pid: 211046, cores: 1)
spawned uWSGI worker 2 (pid: 211047, cores: 1)
spawned uWSGI worker 3 (pid: 211048, cores: 1)
spawned uWSGI worker 4 (pid: 211049, cores: 1)
spawned uWSGI worker 5 (pid: 211050, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 211049|app: -1|req: -1/1] 202.91.80.214 () {60 vars in 1055 bytes} [Mon Aug 14 21:02:12 2023] GET / => generated 21 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 211049|app: -1|req: -1/2] 202.91.80.214 () {56 vars in 960 bytes} [Mon Aug 14 21:02:12 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 211049|app: -1|req: -1/3] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:08:41 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 211049|app: -1|req: -1/4] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:08:43 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Mon Aug 14 21:18:18 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x556040375420
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 211575)
spawned uWSGI worker 1 (pid: 211583, cores: 1)
spawned uWSGI worker 2 (pid: 211584, cores: 1)
spawned uWSGI worker 3 (pid: 211585, cores: 1)
spawned uWSGI worker 4 (pid: 211586, cores: 1)
spawned uWSGI worker 5 (pid: 211587, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 211586|app: -1|req: -1/1] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:18:33 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 211586|app: -1|req: -1/2] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:18:34 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 211586|app: -1|req: -1/3] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:18:41 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 211586|app: -1|req: -1/4] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:18:42 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Mon Aug 14 21:19:13 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55607b066420
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 211608)
spawned uWSGI worker 1 (pid: 211609, cores: 1)
spawned uWSGI worker 2 (pid: 211610, cores: 1)
spawned uWSGI worker 3 (pid: 211611, cores: 1)
spawned uWSGI worker 4 (pid: 211612, cores: 1)
spawned uWSGI worker 5 (pid: 211613, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 211612|app: -1|req: -1/1] 202.91.80.214 () {52 vars in 787 bytes} [Mon Aug 14 21:20:50 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Tue Aug 15 13:57:48 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-24-cloud-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7844
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563e36d53410
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 506)
spawned uWSGI worker 1 (pid: 700, cores: 1)
spawned uWSGI worker 2 (pid: 701, cores: 1)
spawned uWSGI worker 3 (pid: 703, cores: 1)
spawned uWSGI worker 4 (pid: 704, cores: 1)
spawned uWSGI worker 5 (pid: 706, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 703|app: -1|req: -1/1] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 13:59:59 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 703|app: -1|req: -1/2] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:03 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 703|app: -1|req: -1/3] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:03 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 703|app: -1|req: -1/4] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:04 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 706|app: -1|req: -1/5] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:04 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 704|app: -1|req: -1/6] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:04 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 704|app: -1|req: -1/7] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:04 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 701|app: -1|req: -1/8] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:04 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 701|app: -1|req: -1/9] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:04 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Tue Aug 15 14:00:24 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-24-cloud-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7844
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55aee9d50410
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1033)
spawned uWSGI worker 1 (pid: 1034, cores: 1)
spawned uWSGI worker 2 (pid: 1035, cores: 1)
spawned uWSGI worker 3 (pid: 1036, cores: 1)
spawned uWSGI worker 4 (pid: 1037, cores: 1)
spawned uWSGI worker 5 (pid: 1038, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 1036|app: -1|req: -1/1] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:27 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1036|app: -1|req: -1/2] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:27 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1036|app: -1|req: -1/3] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:28 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1036|app: -1|req: -1/4] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:28 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1038|app: -1|req: -1/5] 202.91.80.214 () {58 vars in 1024 bytes} [Tue Aug 15 14:00:53 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1035|app: -1|req: -1/6] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:53 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1037|app: -1|req: -1/7] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:00:57 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1034|app: -1|req: -1/8] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:00:57 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Tue Aug 15 14:01:17 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-24-cloud-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7844
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ea845cc410
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1054)
spawned uWSGI worker 1 (pid: 1055, cores: 1)
spawned uWSGI worker 2 (pid: 1056, cores: 1)
spawned uWSGI worker 3 (pid: 1057, cores: 1)
spawned uWSGI worker 4 (pid: 1058, cores: 1)
spawned uWSGI worker 5 (pid: 1059, cores: 1)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Tue Aug 15 14:06:09 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-24-cloud-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7844
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x561ca58db410
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1104)
spawned uWSGI worker 1 (pid: 1106, cores: 1)
spawned uWSGI worker 2 (pid: 1107, cores: 1)
spawned uWSGI worker 3 (pid: 1108, cores: 1)
spawned uWSGI worker 4 (pid: 1109, cores: 1)
spawned uWSGI worker 5 (pid: 1110, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 1110|app: -1|req: -1/1] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:24:59 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1107|app: -1|req: -1/2] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:24:59 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/bruikey03/shaunslib/app.sock removed.
*** Starting uWSGI 2.0.22 (64bit) on [Tue Aug 15 14:27:47 2023] ***
compiled with version: 10.2.1 20210110 on 01 August 2023 11:53:01
os: Linux-5.10.0-24-cloud-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08)
nodename: shaunslib
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/bruikey03/shaunslib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 7844
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/bruikey03/shaunslib/app.sock fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55595f1aa410
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app
  File "./app.py", line 7, in <module>
    db.init_app(app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 329, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1225)
spawned uWSGI worker 1 (pid: 1228, cores: 1)
spawned uWSGI worker 2 (pid: 1229, cores: 1)
spawned uWSGI worker 3 (pid: 1230, cores: 1)
spawned uWSGI worker 4 (pid: 1231, cores: 1)
spawned uWSGI worker 5 (pid: 1232, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/1] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 14:29:33 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/2] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 14:29:33 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1231|app: -1|req: -1/3] 162.243.141.14 () {38 vars in 573 bytes} [Tue Aug 15 14:50:05 2023] GET /owa/auth/x.js => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/4] 128.199.109.77 () {36 vars in 420 bytes} [Tue Aug 15 15:06:25 2023] GET /ab2g => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1231|app: -1|req: -1/5] 128.199.109.77 () {36 vars in 420 bytes} [Tue Aug 15 15:06:25 2023] GET /ab2h => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/6] 128.199.109.77 () {36 vars in 502 bytes} [Tue Aug 15 15:06:26 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1231|app: -1|req: -1/7] 128.199.109.77 () {36 vars in 406 bytes} [Tue Aug 15 15:06:27 2023] GET /t4 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/8] 128.199.109.77 () {36 vars in 524 bytes} [Tue Aug 15 15:06:27 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/9] 128.199.109.77 () {40 vars in 584 bytes} [Tue Aug 15 15:06:28 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1230|app: -1|req: -1/10] 162.243.137.18 () {36 vars in 426 bytes} [Tue Aug 15 15:09:14 2023] GET /version => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/11] 172.104.11.46 () {36 vars in 504 bytes} [Tue Aug 15 15:48:26 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/12] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 15:50:50 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1230|app: -1|req: -1/13] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 15:50:50 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1230|app: -1|req: -1/14] 202.91.80.214 () {60 vars in 1055 bytes} [Tue Aug 15 15:51:18 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1231|app: -1|req: -1/15] 202.91.80.214 () {56 vars in 960 bytes} [Tue Aug 15 15:51:18 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1230|app: -1|req: -1/16] 202.91.80.214 () {52 vars in 787 bytes} [Tue Aug 15 15:52:05 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1231|app: -1|req: -1/17] 202.91.80.214 () {50 vars in 734 bytes} [Tue Aug 15 15:52:05 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1232|app: -1|req: -1/18] 202.91.80.214 () {52 vars in 787 bytes} [Tue Aug 15 15:55:28 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1231|app: -1|req: -1/19] 202.91.80.214 () {52 vars in 787 bytes} [Tue Aug 15 16:24:36 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1228|app: -1|req: -1/20] 202.91.80.214 () {50 vars in 734 bytes} [Tue Aug 15 16:24:36 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
